"""Result-anchor insertion: include maintenance, degrade path, macros write (DB, CI)."""

from __future__ import annotations

import uuid
from types import SimpleNamespace

from .helpers import csrf_headers, register

_MACROS_TEX = "% Auto-generated by ResearchOS.\n\\newcommand{\\ROSBestAcc}{92.41}\n"


class _FakeAnchorService:
    """Stands in for researchos.figures.anchor_service.ResultAnchorService."""

    found: bool = True

    def __init__(self, db) -> None:
        self.db = db

    async def get_anchor(self, project_id, latex_project_id, macro):
        if not self.found:
            return None
        return SimpleNamespace(
            macro_name="ROSBestAcc",
            anchors_file_path="results/anchors.tex",
            formatted_value="92.41",
            experiment_id=uuid.uuid4(),
            run_id=None,
        )

    async def render_macros(self, project_id) -> str:
        return _MACROS_TEX


def _boom() -> type:
    raise ImportError("figures partition not built")


async def _paper_project(client, email: str) -> tuple[str, str]:
    await register(client, email=email)
    org_id = (await client.get("/organizations")).json()[0]["id"]
    h = csrf_headers(client)
    project_id = (
        await client.post("/projects", json={"organization_id": org_id, "name": "P"}, headers=h)
    ).json()["id"]
    lp_id = (
        await client.post(
            f"/projects/{project_id}/latex-projects", json={"name": "Paper"}, headers=h
        )
    ).json()["id"]
    return project_id, lp_id


def _base(p: str, lp: str) -> str:
    return f"/projects/{p}/latex-projects/{lp}"


async def test_insert_degrades_when_figures_unavailable(client, monkeypatch) -> None:
    monkeypatch.setattr("researchos.documents.anchors._load_anchor_service", _boom)
    p, lp = await _paper_project(client, "anc-degrade@example.com")
    h = csrf_headers(client)

    resp = await client.post(
        f"{_base(p, lp)}/anchors/insert", json={"macro_name": "ResBestAcc"}, headers=h
    )
    assert resp.status_code == 200
    body = resp.json()
    assert body["snippet"] == "\\ResBestAcc{}"
    assert body["validated"] is False
    assert body["include_added"] is True
    assert body["files"] == [{"path": "main.tex", "version": 2}]

    content = (
        await client.get(f"{_base(p, lp)}/files/content?path=main.tex")
    ).json()["content"]
    lines = content.split("\n")
    idx = lines.index("\\begin{document}")
    assert lines[idx + 1] == "\\input{results/anchors}"

    # Idempotent: the include is added exactly once.
    again = (
        await client.post(
            f"{_base(p, lp)}/anchors/insert", json={"macro_name": "ResBestAcc"}, headers=h
        )
    ).json()
    assert again["include_added"] is False
    content2 = (
        await client.get(f"{_base(p, lp)}/files/content?path=main.tex")
    ).json()["content"]
    assert content2.count("\\input{results/anchors}") == 1


async def test_validated_insert_materializes_macros_file(client, monkeypatch) -> None:
    monkeypatch.setattr(
        "researchos.documents.anchors._load_anchor_service", lambda: _FakeAnchorService
    )
    _FakeAnchorService.found = True
    p, lp = await _paper_project(client, "anc-valid@example.com")
    h = csrf_headers(client)

    resp = await client.post(
        f"{_base(p, lp)}/anchors/insert", json={"macro_name": "ROSBestAcc"}, headers=h
    )
    assert resp.status_code == 200
    body = resp.json()
    assert body["validated"] is True
    assert body["snippet"] == "\\ROSBestAcc{}"
    files = {f["path"]: f["version"] for f in body["files"]}
    assert files == {"main.tex": 2, "results/anchors.tex": 1}

    macros = (
        await client.get(f"{_base(p, lp)}/files/content?path=results/anchors.tex")
    ).json()
    assert macros["content"] == _MACROS_TEX
    assert macros["version"] == 1

    # Re-insert: same macros content -> no new version anywhere.
    again = (
        await client.post(
            f"{_base(p, lp)}/anchors/insert", json={"macro_name": "ROSBestAcc"}, headers=h
        )
    ).json()
    assert again["include_added"] is False
    files_again = {f["path"]: f["version"] for f in again["files"]}
    assert files_again == {"main.tex": 2, "results/anchors.tex": 1}


async def test_validated_insert_unknown_anchor_404(client, monkeypatch) -> None:
    monkeypatch.setattr(
        "researchos.documents.anchors._load_anchor_service", lambda: _FakeAnchorService
    )
    _FakeAnchorService.found = False
    p, lp = await _paper_project(client, "anc-404@example.com")
    h = csrf_headers(client)

    resp = await client.post(
        f"{_base(p, lp)}/anchors/insert", json={"macro_name": "ROSMissing"}, headers=h
    )
    assert resp.status_code == 404
    assert resp.json()["error"]["code"] == "anchor_not_found"


async def test_insert_at_splices_snippet_server_side(client, monkeypatch) -> None:
    monkeypatch.setattr("researchos.documents.anchors._load_anchor_service", _boom)
    p, lp = await _paper_project(client, "anc-splice@example.com")
    h = csrf_headers(client)

    resp = await client.post(
        f"{_base(p, lp)}/anchors/insert",
        json={
            "macro_name": "ResBestAcc",
            "target_path": "main.tex",
            "expected_version": 1,
            "insert_at": {"line": 6, "col": 1},
        },
        headers=h,
    )
    assert resp.status_code == 200
    content = (
        await client.get(f"{_base(p, lp)}/files/content?path=main.tex")
    ).json()["content"]
    assert "\\ResBestAcc{}" in content


async def test_insert_cas_staleness_409(client, monkeypatch) -> None:
    monkeypatch.setattr("researchos.documents.anchors._load_anchor_service", _boom)
    p, lp = await _paper_project(client, "anc-cas@example.com")
    h = csrf_headers(client)

    resp = await client.post(
        f"{_base(p, lp)}/anchors/insert",
        json={"macro_name": "ResBestAcc", "expected_version": 99},
        headers=h,
    )
    assert resp.status_code == 409
    assert resp.json()["error"]["code"] == "document_version_conflict"


async def test_bad_macro_name_422(client) -> None:
    p, lp = await _paper_project(client, "anc-badname@example.com")
    h = csrf_headers(client)
    for bad in ["1Bad", "Res_Best", "Res1", ""]:
        resp = await client.post(
            f"{_base(p, lp)}/anchors/insert", json={"macro_name": bad}, headers=h
        )
        assert resp.status_code == 422, bad
