"""Auditable capability ledger for every runtime agent."""

from __future__ import annotations

from researchos.agents.enums import AgentType
from researchos.agents.schemas import AgentCapabilityResponse


def capability_ledger() -> list[AgentCapabilityResponse]:
    rows = [
        (
            AgentType.RESEARCH,
            "Evidence researcher",
            "Hybrid RAG and source-backed synthesis",
            ["question", "project corpus"],
            "research-answer/v1",
            ["knowledge.rag_search", "paper.search", "library.list", "paper.sections"],
            "read-only",
            ["cannot invent citations"],
        ),
        (
            AgentType.READING_CARD,
            "Paper reader",
            "Extract summary, results, code, ideas, benchmarks, ablations, and tuples",
            ["mission_id", "paper_id", "selected sections"],
            "reading-card/v2",
            [],
            "writes versioned card",
            ["exact quotes required", "human review before trusted"],
        ),
        (
            AgentType.IDEA_EXPLORER,
            "Idea explorer",
            "Rank up to ten falsifiable directions from all paper insights",
            ["mission_id", "ranked evidence slate"],
            "direction-slate/v1",
            [],
            "creates draft ideas",
            ["paper ids are allowlisted", "direction approval policy applies"],
        ),
        (
            AgentType.BENCHMARK,
            "Benchmark planner",
            "Rank credible benchmarks and design pilot/full ablation matrices",
            ["mission_id", "paper benchmark evidence"],
            "benchmark-plan/v1",
            [],
            "plan only",
            ["no unreported datasets or metrics", "full compute gate"],
        ),
        (
            AgentType.CRITIC,
            "Novelty critic",
            "Challenge novelty, baselines, datasets, and reproducibility",
            ["idea_id", "library"],
            "critique/v1",
            ["library.list"],
            "advisory",
            ["cannot approve a direction"],
        ),
        (
            AgentType.LEADER,
            "Research lead",
            "Choose one next bounded action and route blockers",
            ["mission_id", "artifacts", "viewer reports"],
            "leader-decision/v1",
            [],
            "control recommendation",
            ["paid APIs and full compute require a gate"],
        ),
        (
            AgentType.CODING,
            "Coding agent",
            "Inspect a workspace and produce a traceable patch",
            ["task", "workspace"],
            "patch-proposal/v1",
            ["workspace.tree", "workspace.read", "workspace.grep"],
            "patch only; optional isolated auto-apply",
            ["read-before-write", "protected paths", "shared workspace apply gate"],
        ),
        (
            AgentType.EXPERIMENT_PLANNER,
            "Experiment planner",
            "Design baselines, benchmarks, metrics, ablations, seeds, and stop rules",
            ["mission review", "paper sections"],
            "experiment-plan/v1",
            [],
            "plan only",
            ["cannot invent results", "compute gate"],
        ),
        (
            AgentType.EXPERIMENT,
            "Experiment analyst",
            "Compute deterministic summaries from recorded metrics",
            ["experiment_run_id"],
            "experiment-analysis/v1",
            [],
            "read-only analysis",
            ["cannot launch or alter results"],
        ),
        (
            AgentType.VIEWER,
            "Viewer / reviewer",
            "Audit a pilot, patch, run, and evidence receipts",
            ["mission_id", "task artifacts", "runs"],
            "viewer-report/v1",
            [],
            "independent advisory",
            ["cannot mutate code or approve itself"],
        ),
        (
            AgentType.PROGRESS,
            "Progress controller",
            "Report live agents, completion, blockers, and next actions",
            ["mission_id", "task graph"],
            "progress-report/v1",
            [],
            "monitor only",
            ["cannot fabricate ETA or completion"],
        ),
        (
            AgentType.WRITER,
            "Paper writer",
            "Draft a venue-aware LaTeX section from verified evidence",
            ["mission_id", "venue", "section"],
            "manuscript-section/v1",
            [],
            "draft artifact",
            ["citation allowlist", "numeric claims require run metrics"],
        ),
        (
            AgentType.DRAWER,
            "Figure and table agent",
            "Create Mermaid method flow, FigureSpecs, tables, and captions",
            ["mission_id", "metrics", "method flow"],
            "figure-bundle/v1",
            [],
            "renders validated figures",
            ["no fabricated values", "Mermaid safety preflight"],
        ),
        (
            AgentType.LATEX,
            "LaTeX editor",
            "Propose tracked prose edits while preserving commands and citations",
            ["document selection", "instruction"],
            "document-suggestion/v1",
            [],
            "suggestion only",
            ["CAS version check", "human accept"],
        ),
        (
            AgentType.REVIEW_SECTION,
            "Review-section writer",
            "Draft one review section from selected evidence",
            ["review section", "paper sections"],
            "review-section/v1",
            [],
            "versioned draft",
            ["exact quote verification"],
        ),
        (
            AgentType.CITATION_ORGANIZER,
            "Citation organizer",
            "Audit metadata, duplicates, and BibTeX",
            ["mission papers"],
            "citation-audit/v1",
            [],
            "metadata artifact",
            ["never guess missing fields"],
        ),
        (
            AgentType.SQL_ANALYST,
            "SQL analyst",
            "Query registered snapshots through a read-only SQL sandbox",
            ["dataset_id", "question"],
            "sql-result/v1",
            [],
            "read-only SQL",
            ["no writes", "no system tables"],
        ),
    ]
    return [
        AgentCapabilityResponse(
            agent_type=agent_type,
            role=role,
            purpose=purpose,
            input_contract=inputs,
            output_contract=output,
            tools=tools,
            autonomy=autonomy,
            approval_boundaries=boundaries,
        )
        for agent_type, role, purpose, inputs, output, tools, autonomy, boundaries in rows
    ]
