"""Pure macros.tex generation over resolved anchors.

Deterministic (sorted by anchor name), always emits one ``\\newcommand`` per
anchor, and never raises for unresolved anchors — the file always compiles.
"""

from __future__ import annotations

import re
import uuid
from dataclasses import dataclass
from datetime import datetime

UNRESOLVED_VALUE = "\\textbf{??}"

# Escape LaTeX-structural characters in a user-supplied suffix so it can never
# break the surrounding \newcommand{...}{value} (a bare "}" closes the brace, a
# bare "%" comments the rest). Characters already backslash-escaped (e.g. the
# common "\%" percent suffix, or "\times") are left intact via the lookbehind.
_SUFFIX_ESCAPE_RE = re.compile(r"(?<!\\)([{}%#&$_])")


def _escape_suffix(suffix: str) -> str:
    return _SUFFIX_ESCAPE_RE.sub(r"\\\1", suffix)


@dataclass(frozen=True)
class ResolvedAnchor:
    """The outcome of resolving one anchor against the current run data."""

    anchor_id: uuid.UUID
    name: str
    experiment_id: uuid.UUID
    experiment_name: str
    run_id: uuid.UUID | None  # concrete source run; None when unresolved
    pinned: bool  # the anchor pins an explicit run
    run_label: str  # run name for pinned anchors, "latest" otherwise
    metric_name: str
    aggregation: str
    value: float | None
    formatted: str  # e.g. "94.21\\%" or the unresolved marker
    resolved: bool


def format_anchor_value(value: float, *, decimals: int, scale: float, suffix: str) -> str:
    """Render ``value * scale`` with fixed decimals plus a LaTeX-safe suffix."""

    return f"{value * scale:.{decimals}f}{_escape_suffix(suffix)}"


def macro_name(anchor_name: str) -> str:
    """Control-word name without the backslash, e.g. ``ROSBestAcc``."""

    return f"ROS{anchor_name}"


def render_macros_tex(
    resolved: list[ResolvedAnchor], *, project_id: uuid.UUID, generated_at: datetime
) -> str:
    lines = [
        "% Auto-generated by ResearchOS. Do not edit. "
        f"Regenerate: GET /projects/{project_id}/anchors/macros.tex",
        f"% generated_at={generated_at.isoformat().replace('+00:00', 'Z')} project={project_id}",
    ]
    for anchor in sorted(resolved, key=lambda a: a.name):
        run_ref = f'run "{anchor.run_label}"' if anchor.pinned else f"run {anchor.run_label}"
        marker = "" if anchor.resolved else " [UNRESOLVED]"
        lines.append(
            f'% \\{macro_name(anchor.name)} <- experiment "{anchor.experiment_name}" '
            f"{run_ref} metric {anchor.metric_name} agg={anchor.aggregation}{marker}"
        )
        value = anchor.formatted if anchor.resolved else UNRESOLVED_VALUE
        lines.append(f"\\newcommand{{\\{macro_name(anchor.name)}}}{{{value}}}")
    return "\n".join(lines) + "\n"
